version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'

  postgres:
    image: postgres:latest
    container_name: investment_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
